### ISSUE TITLE
NullPointerException when transitioning to post-build steps with AccuRev Plugin

### ISSUE THREAD

**Issue by srudolph-credera** [jenkinsci/accurev-plugin#69]
When using the AccuRev Plugin, version 0.7.19 with Jenkins 2.164.1, when the post-build actions trigger, I get a null pointer exception:

FATAL: null
java.lang.NullPointerException
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:640)
	at hudson.model.Run.execute(Run.java:1841)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)

Looking at AbstractBuild.java (https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/AbstractBuild.java), it looks like the collection of culprits from the AccuRev Plugin probably contains a null value

Is it possible that src/main/java/hudson/plugins/accurev/parsers/xml/ParseHistory.java or src/main/java/hudson/plugins/accurev/ParseChangeLog.java are setting null users? I'm new to both code bases, so forgive me if I'm way off base.

**Comment by ivkrishna-mf** [comment]
@srudolph-credera  Can you please provide exact steps to reproduce the issue ?

**Comment by srudolph-credera** [comment]
@ivkrishna-mf - This happens 100% of the time on all of our standard Jenkins jobs that use the AccuRev plugin for source code management and occurs when the post build actions section triggers, regardless of whether or not there are post build actions and what those actions are. Switching to a Jenkins pipeline translation of the same job avoids the NullPointerException.

**Comment by eagle79** [comment]
We are seeing this too. Also, see [JENKINS-56882](https://issues.jenkins-ci.org/browse/JENKINS-56882)

**Comment by itavero** [comment]
I'm also seeing this. In my particular case, we had a new member join our team and she had never logged in to Jenkins CI yet, but did promote changes in AccuRev using her own account.
This meant that the user was not yet known in Jenkins CI, so I figured this might be related.
I've just asked her to log in to Jenkins CI ones and I'm rerunning the build that failed with this NPE now. Let's hope it succeeds this time. Perhaps that might give some useful information about the root cause.

**Comment by itavero** [comment]
I think this piece of code might be the issue:

https://github.com/jenkinsci/accurev-plugin/blob/be80d3c503ed36327c782f18ece66ad4f4749862/src/main/java/hudson/plugins/accurev/AccurevTransaction.java#L99-L101

Several other methods refer to this `author` field (so, `toString()`, `getUser()` and `getAuthor()` and might therefor be accessing `null`.

Does it make sense to pass `true` instead so that new users are actually created?

**Comment by itavero** [comment]
If my suggestions sounds good, I can make a PR to change that line of code.

FYI: This plugin is looking for a new maintainer.
I thought about becoming the maintainer, but given that we are actually planning to migrate from AccuRev to Git, that would be a very short-term solution.

**Comment by jetersen** [comment]
I believe most others VCS plugins uses false as well.

**Comment by jetersen** [comment]
Properly better to change the code to adding annotation for author to check for null.

**Comment by jetersen** [comment]
Nvm: https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/hudson/plugins/git/GitChangeSet.java#L403
Git will create the user.

**Comment by isaacchou** [comment]
@jetersen 

Can you link pull request #91 to this issue?  I have reviewed and tested the proposed code change but have no permission to link the PR to this issue.  Thanks!

**Comment by isaacchou** [comment]
Thank you @jetersen for linking #91. I have updated the PR with my code review feedback.  If you agree with my assessment of the proposed change and behavior, can you merge the code and close the pull request?
